# Generated by Django 4.1.7 on 2023-03-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
