# Generated by Django 4.1.7 on 2023-03-27 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('prix_per_night', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nombre_etoiles', models.CharField(max_length=10)),
                ('url', models.URLField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.city')),
            ],
        ),
    ]
